name: Build and Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --windowed --icon=icons/app.ico object_studio.py

      - name: Zip folder
        run: |
          Compress-Archive -Path dist/object_studio/* -DestinationPath dist/object_studio_windows.zip

      - name: Release EXE
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Version ${{ github.ref_name }}
          files: dist/object_studio_windows.zip

  mac-intel-build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build APP
        run: |
          pyinstaller --windowed --icon=icons/app.icns --osx-bundle-identifier=com.wraithfire.objectstudio object_studio.py

      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg "object_studio.dmg" dist/object_studio.app
          mv *.dmg object_studio_mac_intel.dmg

      - name: Release DMG
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Version ${{ github.ref_name }}
          files: object_studio_mac_intel.dmg

  mac-arm64-build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build App
        run: |
          pyinstaller --windowed --icon=icons/app.icns --osx-bundle-identifier=com.wraithfire.objectstudio object_studio.py

      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg "object_studio.dmg" dist/object_studio.app
          mv *.dmg object_studio_mac_arm64.dmg

      - name: Release DMG
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Version ${{ github.ref_name }}
          files: object_studio_mac_arm64.dmg
